---
inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'doc/**/*'
    - 'test/**/*'
    - 'pkg/**/*'
    - 'resources/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
