require "active_support/core_ext/string"
require "active_support/core_ext/hash"
require "speedflow/version"
require "speedflow/configuration"
require "speedflow/command"
require "speedflow/commands/abstract"
require "speedflow/commands/default"
require "speedflow/commands/init"
